tunnel: 5ab11241-05af-4e38-82da-ec7cac8656c2
protocol: http2
ingress:
  - hostname: atlas.ostwald.top
    service: http://127.0.0.1:3000
  - hostname: apiatlas.ostwald.top
    service: http://127.0.0.1:3000
  - service: http_status:404
