
services:

# =========================
# BACKEND NODEJS
# =========================
backend:
  build:
    context: .
    dockerfile: backend.Dockerfile
    
    container_name: meu_backend
    
    ports:
      - "8080:8080"
      
      working_dir: /app
      
      restart: unless-stopped
      
      #MUDE PARA A PASTA QUE PREFERIR DENTRO DO LINUX QUE SEU ATLAS irá rodar!.
      #ex: /usr/atlas-server/atlas-logs:/app/logs
      # recomendo não mudar após os ":". deixe ":/app/exemple"
      volumes:
        - /home/ostwaldz/atlas-server/atlas-logs:/app/logs
        - /home/ostwaldz/atlas-server/atlas-vaults:/app/vaults
        - /home/ostwaldz/atlas-server/atlas-cloud:/app/cloud
        
        
        depends_on:
          mysql:
            condition: service_healthy   # <-- espera o MySQL estar saudável
            
            # =========================
            # FRONTEND NGINX
            # =========================
            frontend:
              image: nginx:latest
              
              container_name: meu_frontend
              
              ports:
                - "3000:80"
                
                volumes:
                  - ./frontend:/usr/share/nginx/html/frontend
                  - ./index.html:/usr/share/nginx/html/index.html
                  - ./nginx.conf:/etc/nginx/conf.d/default.conf
                  
                  restart: unless-stopped
                  
                  depends_on:
                    backend:
                      condition: service_started
                      
                      # =========================
                      # MYSQL SERVER
                      # =========================
                      mysql:
                        image: mysql:8.0
                        
                        container_name: meu_mysql
                        
                        restart: unless-stopped
                        
                        environment:
                          MYSQL_ROOT_PASSWORD: ogwdamigodoben10
                          
                          ports:
                            - "3306:3306"
                            
                            volumes:
                              - mysql_data:/var/lib/mysql
                              # ✅ caminho corrigido para onde o SQL realmente está no repo
                              - ./backend/estrutura_banco_MySQL.sql:/docker-entrypoint-initdb.d/estrutura_banco_MySQL.sql
                              
                              healthcheck:                          # <-- MySQL avisa quando tá pronto
                              test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pogwdamigodoben10"]
                              interval: 10s
                              timeout: 10s
                              retries: 10
                              start_period: 180s
                              
                              
volumes:
                              mysql_data:
                                